### ISSUE TITLE
Failed to load puploc.bin

### ISSUE THREAD

**Issue by energo5** [tehnokv/picojs#25]
Hello.
Your example https://tehnokv.com/posts/puploc-with-trees/demo/ print error:
[Error] Failed to load resource: https://f002.backblazeb2.com/file/tehnokv-www/posts/puploc-with-trees/demo/puploc.bin

Have you this file in another place? Can you write new place of this file?

**Comment by vispa78** [comment]
It seems it's here:
https://tehnokv.com/posts/puploc-with-trees/demo/puploc.bin
