### ISSUE TITLE
can not recognize face as follow..

### ISSUE THREAD

**Issue by alex2wong** [tehnokv/picojs#7]
![](https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1676671064,1587953906&fm=27&gp=0.jpg)

**Comment by Sherryer** [comment]
看来引入的模型还不支持这张脸:)

**Comment by alex2wong** [comment]
It may because the model trained has not consider face-rotated. but we can not demand less than 200 lines of code to do much. This repo is a good start anyway.
